os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode8
install:
  - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)"
script:
  - make
  - make test
addons:
    code_climate:
        repo_token: 4a50f87b4b62b83f0e28403ae130ffc297479000b4b16962cb8387dfcb908413
